/**
 * Created by rob on 3/24/2017.
 */
const querystring = require('querystring');
const himalaya = require('himalaya');
const he = require('he');
let resp = {
    "header": {
        "type": "esummary",
        "version": "0.3"
    },
    "result": {
        "4141594": {
            "uid": "4141594",
            "title": "Table",
            "pubdate": "2015/10/22 00:00",
            "id": "nap21799/appB/table/tab_appB-2/PMC",
            "accessionid": "NBK327243",
            "parents": "",
            "rtype": "table",
            "rid": "NBK327243/table/tab_appB-2",
            "text": "",
            "bookinfo": "&lt;Info&gt;&lt;Path&gt;&lt;Parent id=\"nap21799\" role=\"source\" type=\"book\" uid=\"4141572\"&gt;&lt;Title&gt;Using Existing Platforms to Integrate and Coordinate Investments for Children: Summary of a Joint Workshop by the National Academies of Sciences, Engineering, and Medicine; Centre for Health Education and Health Promotion; and Wu Yee Sun College of the Chinese University of Hong Kong&lt;/Title&gt;&lt;/Parent&gt;&lt;Parent id=\"appB\" role=\"document\" type=\"appendix\" uid=\"4141590\"&gt;&lt;Title&gt;Workshop Agenda&lt;/Title&gt;&lt;/Parent&gt;&lt;Self id=\"tab_appB-2\" role=\"object\" type=\"table\" uid=\"4141594\"&gt;&lt;Title&gt;Table&lt;/Title&gt;&lt;/Self&gt;&lt;/Path&gt;&lt;Citation CitationType=\"Object\"&gt;&lt;MainRecord&gt;&lt;Title&gt;Table.&lt;/Title&gt;&lt;/MainRecord&gt;&lt;ParentRecord&gt;&lt;Title&gt;Using Existing Platforms to Integrate and Coordinate Investments for Children: Summary of a Joint Workshop by the National Academies of Sciences, Engineering, and Medicine; Centre for Health Education and Health Promotion; and Wu Yee Sun College of the Chinese University of Hong Kong.&lt;/Title&gt;&lt;Contributors&gt;Forum on Investing in Young Children Globally; Board on Global Health; Board on Children, Youth, and Families; Institute of Medicine; Division of Behavioral and Social Sciences and Education; National Academies of Sciences, Engineering, and Medicine.&lt;/Contributors&gt;&lt;PublicationStatement&gt;Washington (DC): National Academies Press (US); 2015 Oct 22.&lt;/PublicationStatement&gt;&lt;/ParentRecord&gt;&lt;Location&gt;Appendix  B, Workshop Agenda&lt;/Location&gt;&lt;/Citation&gt;&lt;/Info&gt;",
            "bookid": 4141572,
            "bookaccessionid": "NBK327252",
            "chapterid": 4141590,
            "chapteraccessionid": "NBK327243",
            "book": "nap21799",
            "navigation": "yes"
        },
        "4141596": {
            "uid": "4141596",
            "title": "Forum on Investing in Young Children Globally (iYCG) Workshop 4: Using Existing Platforms to Integrate and Coordinate Investments for Children",
            "pubdate": "2015/10/22 00:00",
            "id": "nap21799/appB/sec/sec_000049/PMC",
            "accessionid": "NBK327243",
            "parents": "",
            "rtype": "sec",
            "rid": "NBK327243/sec_000049",
            "text": "",
            "bookinfo": "&lt;Info&gt;&lt;Path&gt;&lt;Parent id=\"nap21799\" role=\"source\" type=\"book\" uid=\"4141572\"&gt;&lt;Title&gt;Using Existing Platforms to Integrate and Coordinate Investments for Children: Summary of a Joint Workshop by the National Academies of Sciences, Engineering, and Medicine; Centre for Health Education and Health Promotion; and Wu Yee Sun College of the Chinese University of Hong Kong&lt;/Title&gt;&lt;/Parent&gt;&lt;Parent id=\"appB\" role=\"document\" type=\"appendix\" uid=\"4141590\"&gt;&lt;Title&gt;Workshop Agenda&lt;/Title&gt;&lt;/Parent&gt;&lt;Self id=\"sec_000049\" role=\"object\" type=\"sec\" uid=\"4141596\"&gt;&lt;Title&gt;Forum on Investing in Young Children Globally (iYCG) Workshop 4: Using Existing Platforms to Integrate and Coordinate Investments for Children&lt;/Title&gt;&lt;/Self&gt;&lt;/Path&gt;&lt;Citation CitationType=\"Object\"&gt;&lt;MainRecord&gt;&lt;Title&gt;Forum on Investing in Young Children Globally (iYCG) Workshop 4: Using Existing Platforms to Integrate and Coordinate Investments for Children.&lt;/Title&gt;&lt;/MainRecord&gt;&lt;ParentRecord&gt;&lt;Title&gt;Using Existing Platforms to Integrate and Coordinate Investments for Children: Summary of a Joint Workshop by the National Academies of Sciences, Engineering, and Medicine; Centre for Health Education and Health Promotion; and Wu Yee Sun College of the Chinese University of Hong Kong.&lt;/Title&gt;&lt;Contributors&gt;Forum on Investing in Young Children Globally; Board on Global Health; Board on Children, Youth, and Families; Institute of Medicine; Division of Behavioral and Social Sciences and Education; National Academies of Sciences, Engineering, and Medicine.&lt;/Contributors&gt;&lt;PublicationStatement&gt;Washington (DC): National Academies Press (US); 2015 Oct 22.&lt;/PublicationStatement&gt;&lt;/ParentRecord&gt;&lt;Location&gt;Appendix  B, Workshop Agenda&lt;/Location&gt;&lt;/Citation&gt;&lt;/Info&gt;",
            "bookid": 4141572,
            "bookaccessionid": "NBK327252",
            "chapterid": 4141590,
            "chapteraccessionid": "NBK327243",
            "book": "nap21799",
            "navigation": "yes"
        },
        "4141616": {
            "uid": "4141616",
            "title": "Acronyms",
            "pubdate": "2015/10/22 00:00",
            "id": "nap21799/appendix/appA/PMC",
            "accessionid": "NBK327256",
            "parents": "",
            "rtype": "appendix",
            "rid": "NBK327256",
            "text": "",
            "bookinfo": "&lt;Info&gt;&lt;Path&gt;&lt;Parent id=\"nap21799\" role=\"source\" type=\"book\" uid=\"4141572\"&gt;&lt;Title&gt;Using Existing Platforms to Integrate and Coordinate Investments for Children: Summary of a Joint Workshop by the National Academies of Sciences, Engineering, and Medicine; Centre for Health Education and Health Promotion; and Wu Yee Sun College of the Chinese University of Hong Kong&lt;/Title&gt;&lt;/Parent&gt;&lt;Self id=\"appA\" role=\"document\" type=\"appendix\" uid=\"4141616\"&gt;&lt;Title&gt;Acronyms&lt;/Title&gt;&lt;/Self&gt;&lt;/Path&gt;&lt;Citation CitationType=\"Part\"&gt;&lt;MainRecord&gt;&lt;Title&gt;Acronyms.&lt;/Title&gt;&lt;/MainRecord&gt;&lt;ParentRecord&gt;&lt;Title&gt;Using Existing Platforms to Integrate and Coordinate Investments for Children: Summary of a Joint Workshop by the National Academies of Sciences, Engineering, and Medicine; Centre for Health Education and Health Promotion; and Wu Yee Sun College of the Chinese University of Hong Kong.&lt;/Title&gt;&lt;Contributors&gt;Forum on Investing in Young Children Globally; Board on Global Health; Board on Children, Youth, and Families; Institute of Medicine; Division of Behavioral and Social Sciences and Education; National Academies of Sciences, Engineering, and Medicine.&lt;/Contributors&gt;&lt;PublicationStatement&gt;Washington (DC): National Academies Press (US); 2015 Oct 22.&lt;/PublicationStatement&gt;&lt;/ParentRecord&gt;&lt;Location&gt;Appendix A&lt;/Location&gt;&lt;/Citation&gt;&lt;/Info&gt;",
            "bookid": 4141572,
            "bookaccessionid": "NBK327252",
            "chapterid": 4141616,
            "chapteraccessionid": "NBK327256",
            "book": "nap21799",
            "navigation": "yes"
        },
        "4141618": {
            "uid": "4141618",
            "title": "Using Existing Platforms to Integrate Services on the Ground",
            "pubdate": "2015/10/22 00:00",
            "id": "nap21799/chapter/ch5/PMC",
            "accessionid": "NBK327245",
            "parents": "",
            "rtype": "chapter",
            "rid": "NBK327245",
            "text": "",
            "bookinfo": "&lt;Info&gt;&lt;Path&gt;&lt;Parent id=\"nap21799\" role=\"source\" type=\"book\" uid=\"4141572\"&gt;&lt;Title&gt;Using Existing Platforms to Integrate and Coordinate Investments for Children: Summary of a Joint Workshop by the National Academies of Sciences, Engineering, and Medicine; Centre for Health Education and Health Promotion; and Wu Yee Sun College of the Chinese University of Hong Kong&lt;/Title&gt;&lt;/Parent&gt;&lt;Self id=\"ch5\" role=\"document\" type=\"chapter\" uid=\"4141618\"&gt;&lt;Title&gt;Using Existing Platforms to Integrate Services on the Ground&lt;/Title&gt;&lt;/Self&gt;&lt;/Path&gt;&lt;Citation CitationType=\"Part\"&gt;&lt;MainRecord&gt;&lt;Title&gt;Using Existing Platforms to Integrate Services on the Ground.&lt;/Title&gt;&lt;/MainRecord&gt;&lt;ParentRecord&gt;&lt;Title&gt;Using Existing Platforms to Integrate and Coordinate Investments for Children: Summary of a Joint Workshop by the National Academies of Sciences, Engineering, and Medicine; Centre for Health Education and Health Promotion; and Wu Yee Sun College of the Chinese University of Hong Kong.&lt;/Title&gt;&lt;Contributors&gt;Forum on Investing in Young Children Globally; Board on Global Health; Board on Children, Youth, and Families; Institute of Medicine; Division of Behavioral and Social Sciences and Education; National Academies of Sciences, Engineering, and Medicine.&lt;/Contributors&gt;&lt;PublicationStatement&gt;Washington (DC): National Academies Press (US); 2015 Oct 22.&lt;/PublicationStatement&gt;&lt;/ParentRecord&gt;&lt;/Citation&gt;&lt;/Info&gt;",
            "bookid": 4141572,
            "bookaccessionid": "NBK327252",
            "chapterid": 4141618,
            "chapteraccessionid": "NBK327245",
            "book": "nap21799",
            "navigation": "yes"
        },
        "4141622": {
            "uid": "4141622",
            "title": "HOLISTIC DEVELOPMENT AND LEARNING IN EARLY CHILDHOOD: INITIAL EXPERIENCES FROM BRAC",
            "pubdate": "2015/10/22 00:00",
            "id": "nap21799/ch5/sec/sec_000036/PMC",
            "accessionid": "NBK327245",
            "parents": "",
            "rtype": "sec",
            "rid": "NBK327245/sec_000036",
            "text": "",
            "bookinfo": "&lt;Info&gt;&lt;Path&gt;&lt;Parent id=\"nap21799\" role=\"source\" type=\"book\" uid=\"4141572\"&gt;&lt;Title&gt;Using Existing Platforms to Integrate and Coordinate Investments for Children: Summary of a Joint Workshop by the National Academies of Sciences, Engineering, and Medicine; Centre for Health Education and Health Promotion; and Wu Yee Sun College of the Chinese University of Hong Kong&lt;/Title&gt;&lt;/Parent&gt;&lt;Parent id=\"ch5\" role=\"document\" type=\"chapter\" uid=\"4141618\"&gt;&lt;Title&gt;Using Existing Platforms to Integrate Services on the Ground&lt;/Title&gt;&lt;/Parent&gt;&lt;Self id=\"sec_000036\" role=\"object\" type=\"sec\" uid=\"4141622\"&gt;&lt;Title&gt;HOLISTIC DEVELOPMENT AND LEARNING IN EARLY CHILDHOOD: INITIAL EXPERIENCES FROM BRAC&lt;/Title&gt;&lt;/Self&gt;&lt;/Path&gt;&lt;Citation CitationType=\"Object\"&gt;&lt;MainRecord&gt;&lt;Title&gt;HOLISTIC DEVELOPMENT AND LEARNING IN EARLY CHILDHOOD: INITIAL EXPERIENCES FROM BRAC.&lt;/Title&gt;&lt;/MainRecord&gt;&lt;ParentRecord&gt;&lt;Title&gt;Using Existing Platforms to Integrate and Coordinate Investments for Children: Summary of a Joint Workshop by the National Academies of Sciences, Engineering, and Medicine; Centre for Health Education and Health Promotion; and Wu Yee Sun College of the Chinese University of Hong Kong.&lt;/Title&gt;&lt;Contributors&gt;Forum on Investing in Young Children Globally; Board on Global Health; Board on Children, Youth, and Families; Institute of Medicine; Division of Behavioral and Social Sciences and Education; National Academies of Sciences, Engineering, and Medicine.&lt;/Contributors&gt;&lt;PublicationStatement&gt;Washington (DC): National Academies Press (US); 2015 Oct 22.&lt;/PublicationStatement&gt;&lt;/ParentRecord&gt;&lt;Location&gt;5, Using Existing Platforms to Integrate Services on the Ground&lt;/Location&gt;&lt;/Citation&gt;&lt;/Info&gt;",
            "bookid": 4141572,
            "bookaccessionid": "NBK327252",
            "chapterid": 4141618,
            "chapteraccessionid": "NBK327245",
            "book": "nap21799",
            "navigation": "yes"
        },
        "4141704": {
            "uid": "4141704",
            "title": "Biographical Sketches of Workshop Speakers",
            "pubdate": "2015/10/22 00:00",
            "id": "nap21799/appendix/chap48/PMC",
            "accessionid": "NBK327242",
            "parents": "",
            "rtype": "appendix",
            "rid": "NBK327242",
            "text": "",
            "bookinfo": "&lt;Info&gt;&lt;Path&gt;&lt;Parent id=\"nap21799\" role=\"source\" type=\"book\" uid=\"4141572\"&gt;&lt;Title&gt;Using Existing Platforms to Integrate and Coordinate Investments for Children: Summary of a Joint Workshop by the National Academies of Sciences, Engineering, and Medicine; Centre for Health Education and Health Promotion; and Wu Yee Sun College of the Chinese University of Hong Kong&lt;/Title&gt;&lt;/Parent&gt;&lt;Self id=\"chap48\" role=\"document\" type=\"appendix\" uid=\"4141704\"&gt;&lt;Title&gt;Biographical Sketches of Workshop Speakers&lt;/Title&gt;&lt;/Self&gt;&lt;/Path&gt;&lt;Citation CitationType=\"Part\"&gt;&lt;MainRecord&gt;&lt;Title&gt;Biographical Sketches of Workshop Speakers.&lt;/Title&gt;&lt;/MainRecord&gt;&lt;ParentRecord&gt;&lt;Title&gt;Using Existing Platforms to Integrate and Coordinate Investments for Children: Summary of a Joint Workshop by the National Academies of Sciences, Engineering, and Medicine; Centre for Health Education and Health Promotion; and Wu Yee Sun College of the Chinese University of Hong Kong.&lt;/Title&gt;&lt;Contributors&gt;Forum on Investing in Young Children Globally; Board on Global Health; Board on Children, Youth, and Families; Institute of Medicine; Division of Behavioral and Social Sciences and Education; National Academies of Sciences, Engineering, and Medicine.&lt;/Contributors&gt;&lt;PublicationStatement&gt;Washington (DC): National Academies Press (US); 2015 Oct 22.&lt;/PublicationStatement&gt;&lt;/ParentRecord&gt;&lt;Location&gt;Appendix C&lt;/Location&gt;&lt;/Citation&gt;&lt;/Info&gt;",
            "bookid": 4141572,
            "bookaccessionid": "NBK327252",
            "chapterid": 4141704,
            "chapteraccessionid": "NBK327242",
            "book": "nap21799",
            "navigation": "yes"
        },
        "4184400": {
            "uid": "4184400",
            "title": "Reviewers",
            "pubdate": "2015/11/19 00:00",
            "id": "nap21736/sec/sec_000005/PMC",
            "accessionid": "NBK333252",
            "parents": "",
            "rtype": "sec",
            "rid": "NBK333252",
            "text": "",
            "bookinfo": "&lt;Info&gt;&lt;Path&gt;&lt;Parent id=\"nap21736\" role=\"source\" type=\"book\" uid=\"4184392\"&gt;&lt;Title&gt;Improving Quality of Care in Low- and Middle-Income Countries: Workshop Summary&lt;/Title&gt;&lt;/Parent&gt;&lt;Self id=\"sec_000005\" role=\"document\" type=\"sec\" uid=\"4184400\"&gt;&lt;Title&gt;Reviewers&lt;/Title&gt;&lt;/Self&gt;&lt;/Path&gt;&lt;Citation CitationType=\"Part\"&gt;&lt;MainRecord&gt;&lt;Title&gt;Reviewers.&lt;/Title&gt;&lt;/MainRecord&gt;&lt;ParentRecord&gt;&lt;Title&gt;Improving Quality of Care in Low- and Middle-Income Countries: Workshop Summary.&lt;/Title&gt;&lt;Contributors&gt;Board on Global Health; Institute of Medicine; The National Academies of Sciences, Engineering, and Medicine.&lt;/Contributors&gt;&lt;PublicationStatement&gt;Washington (DC): National Academies Press (US); 2015 Nov 19.&lt;/PublicationStatement&gt;&lt;/ParentRecord&gt;&lt;/Citation&gt;&lt;/Info&gt;",
            "bookid": 4184392,
            "bookaccessionid": "NBK333246",
            "chapterid": 4184400,
            "chapteraccessionid": "NBK333252",
            "book": "nap21736",
            "navigation": "yes"
        },
        "4211182": {
            "uid": "4211182",
            "title": "Contributors",
            "pubdate": "2015/11/01 00:00",
            "id": "dcp3v3/sec/bm3/PMC",
            "accessionid": "NBK343641",
            "parents": "",
            "rtype": "sec",
            "rid": "NBK343641",
            "text": "",
            "bookinfo": "&lt;Info&gt;&lt;Path&gt;&lt;Parent id=\"dcp3v3\" role=\"source\" type=\"book\" uid=\"4211144\"&gt;&lt;Title&gt;Cancer: Disease Control Priorities, Third Edition (Volume 3)&lt;/Title&gt;&lt;/Parent&gt;&lt;Self id=\"bm3\" role=\"document\" type=\"sec\" uid=\"4211182\"&gt;&lt;Title&gt;Contributors&lt;/Title&gt;&lt;/Self&gt;&lt;/Path&gt;&lt;Citation CitationType=\"Part\"&gt;&lt;MainRecord&gt;&lt;Title&gt;Contributors.&lt;/Title&gt;&lt;/MainRecord&gt;&lt;ParentRecord&gt;&lt;Title&gt;Cancer: Disease Control Priorities, Third Edition (Volume 3).&lt;/Title&gt;&lt;Contributors&gt;Gelband H, Jha P, Sankaranarayanan R, et al., editors.&lt;/Contributors&gt;&lt;PublicationStatement&gt;Washington (DC): The International Bank for Reconstruction and Development / The World Bank; 2015 Nov 1.&lt;/PublicationStatement&gt;&lt;/ParentRecord&gt;&lt;/Citation&gt;&lt;/Info&gt;",
            "bookid": 4211144,
            "bookaccessionid": "NBK343628",
            "chapterid": 4211182,
            "chapteraccessionid": "NBK343641",
            "book": "dcp3v3",
            "navigation": "yes"
        },
        "4229776": {
            "uid": "4229776",
            "title": "Biographical Sketches of Workshop Speakers",
            "pubdate": "2016/03/03 00:00",
            "id": "nap21883/appendix/appC/PMC",
            "accessionid": "NBK355331",
            "parents": "",
            "rtype": "appendix",
            "rid": "NBK355331",
            "text": "",
            "bookinfo": "&lt;Info&gt;&lt;Path&gt;&lt;Parent id=\"nap21883\" role=\"source\" type=\"book\" uid=\"4229206\"&gt;&lt;Title&gt;Supporting Family and Community Investments in Young Children Globally: Summary of a Joint Workshop by the National Academies of Sciences, Engineering, and Medicine and the Ethiopian Academy of Sciences&lt;/Title&gt;&lt;/Parent&gt;&lt;Self id=\"appC\" role=\"document\" type=\"appendix\" uid=\"4229776\"&gt;&lt;Title&gt;Biographical Sketches of Workshop Speakers&lt;/Title&gt;&lt;/Self&gt;&lt;/Path&gt;&lt;Citation CitationType=\"Part\"&gt;&lt;MainRecord&gt;&lt;Title&gt;Biographical Sketches of Workshop Speakers.&lt;/Title&gt;&lt;/MainRecord&gt;&lt;ParentRecord&gt;&lt;Title&gt;Supporting Family and Community Investments in Young Children Globally: Summary of a Joint Workshop by the National Academies of Sciences, Engineering, and Medicine and the Ethiopian Academy of Sciences.&lt;/Title&gt;&lt;Contributors&gt;Forum on Investing in Young Children Globally; Board on Global Health; Board on Children, Youth, and Families; Institute of Medicine; Division of Behavioral and Social Sciences and Education; National Academies of Sciences, Engineering, and Medicine.&lt;/Contributors&gt;&lt;PublicationStatement&gt;Washington (DC): National Academies Press (US); 2016 Mar 3.&lt;/PublicationStatement&gt;&lt;/ParentRecord&gt;&lt;Location&gt;Appendix C&lt;/Location&gt;&lt;/Citation&gt;&lt;/Info&gt;",
            "bookid": 4229206,
            "bookaccessionid": "NBK350742",
            "chapterid": 4229776,
            "chapteraccessionid": "NBK355331",
            "book": "nap21883",
            "navigation": "yes"
        },
        "4263754": {
            "uid": "4263754",
            "title": "Workshop Speaker Biographies",
            "pubdate": "2016/05/11 00:00",
            "id": "nap21854/appendix/appE/PMC",
            "accessionid": "NBK362970",
            "parents": "",
            "rtype": "appendix",
            "rid": "NBK362970",
            "text": "",
            "bookinfo": "&lt;Info&gt;&lt;Path&gt;&lt;Parent id=\"nap21854\" role=\"source\" type=\"book\" uid=\"4215384\"&gt;&lt;Title&gt;Global Health Risk Framework: Governance for Global Health: Workshop Summary&lt;/Title&gt;&lt;/Parent&gt;&lt;Self id=\"appE\" role=\"document\" type=\"appendix\" uid=\"4263754\"&gt;&lt;Title&gt;Workshop Speaker Biographies&lt;/Title&gt;&lt;/Self&gt;&lt;/Path&gt;&lt;Citation CitationType=\"Part\"&gt;&lt;MainRecord&gt;&lt;Title&gt;Workshop Speaker Biographies.&lt;/Title&gt;&lt;/MainRecord&gt;&lt;ParentRecord&gt;&lt;Title&gt;Global Health Risk Framework: Governance for Global Health: Workshop Summary.&lt;/Title&gt;&lt;Contributors&gt;Forum on Microbial Threats; Board on Global Health; Institute of Medicine; National Academies of Sciences, Engineering, and Medicine.&lt;/Contributors&gt;&lt;PublicationStatement&gt;Washington (DC): National Academies Press (US); 2016 May 11.&lt;/PublicationStatement&gt;&lt;/ParentRecord&gt;&lt;/Citation&gt;&lt;/Info&gt;",
            "bookid": 4215384,
            "bookaccessionid": "NBK349074",
            "chapterid": 4263754,
            "chapteraccessionid": "NBK362970",
            "book": "nap21854",
            "navigation": "yes"
        },
        "4284158": {
            "uid": "4284158",
            "title": "INTERNATIONAL OVERSIGHT GROUP",
            "pubdate": "2016/05/16 00:00",
            "id": "nap21891/sec/sec_000005/PMC",
            "accessionid": "NBK368402",
            "parents": "",
            "rtype": "sec",
            "rid": "NBK368402",
            "text": "",
            "bookinfo": "&lt;Info&gt;&lt;Path&gt;&lt;Parent id=\"nap21891\" role=\"source\" type=\"book\" uid=\"4284076\"&gt;&lt;Title&gt;The Neglected Dimension of Global Security: A Framework to Counter Infectious Disease Crises&lt;/Title&gt;&lt;/Parent&gt;&lt;Self id=\"sec_000005\" role=\"document\" type=\"sec\" uid=\"4284158\"&gt;&lt;Title&gt;INTERNATIONAL OVERSIGHT GROUP&lt;/Title&gt;&lt;/Self&gt;&lt;/Path&gt;&lt;Citation CitationType=\"Part\"&gt;&lt;MainRecord&gt;&lt;Title&gt;INTERNATIONAL OVERSIGHT GROUP.&lt;/Title&gt;&lt;/MainRecord&gt;&lt;ParentRecord&gt;&lt;Title&gt;The Neglected Dimension of Global Security: A Framework to Counter Infectious Disease Crises.&lt;/Title&gt;&lt;Contributors&gt;Commission on a Global Health Risk Framework for the Future; National Academy of Medicine, Secretariat.&lt;/Contributors&gt;&lt;PublicationStatement&gt;Washington (DC): National Academies Press (US); 2016 May 16.&lt;/PublicationStatement&gt;&lt;/ParentRecord&gt;&lt;/Citation&gt;&lt;/Info&gt;",
            "bookid": 4284076,
            "bookaccessionid": "NBK368394",
            "chapterid": 4284158,
            "chapteraccessionid": "NBK368402",
            "book": "nap21891",
            "navigation": "yes"
        },
        "4284246": {
            "uid": "4284246",
            "title": "INTERNATIONAL OVERSIGHT GROUP",
            "pubdate": "2016/05/16 00:00",
            "id": "nap21891/appD/sec/sec_000134/PMC",
            "accessionid": "NBK368396",
            "parents": "",
            "rtype": "sec",
            "rid": "NBK368396/sec_000134",
            "text": "",
            "bookinfo": "&lt;Info&gt;&lt;Path&gt;&lt;Parent id=\"nap21891\" role=\"source\" type=\"book\" uid=\"4284076\"&gt;&lt;Title&gt;The Neglected Dimension of Global Security: A Framework to Counter Infectious Disease Crises&lt;/Title&gt;&lt;/Parent&gt;&lt;Parent id=\"appD\" role=\"document\" type=\"appendix\" uid=\"4284242\"&gt;&lt;Title&gt;Biographical Sketches of Commission Members, Consultants, and Staff&lt;/Title&gt;&lt;/Parent&gt;&lt;Self id=\"sec_000134\" role=\"object\" type=\"sec\" uid=\"4284246\"&gt;&lt;Title&gt;INTERNATIONAL OVERSIGHT GROUP&lt;/Title&gt;&lt;/Self&gt;&lt;/Path&gt;&lt;Citation CitationType=\"Object\"&gt;&lt;MainRecord&gt;&lt;Title&gt;INTERNATIONAL OVERSIGHT GROUP.&lt;/Title&gt;&lt;/MainRecord&gt;&lt;ParentRecord&gt;&lt;Title&gt;The Neglected Dimension of Global Security: A Framework to Counter Infectious Disease Crises.&lt;/Title&gt;&lt;Contributors&gt;Commission on a Global Health Risk Framework for the Future; National Academy of Medicine, Secretariat.&lt;/Contributors&gt;&lt;PublicationStatement&gt;Washington (DC): National Academies Press (US); 2016 May 16.&lt;/PublicationStatement&gt;&lt;/ParentRecord&gt;&lt;Location&gt;Appendix  D, Biographical Sketches of Commission Members, Consultants, and Staff&lt;/Location&gt;&lt;/Citation&gt;&lt;/Info&gt;",
            "bookid": 4284076,
            "bookaccessionid": "NBK368394",
            "chapterid": 4284242,
            "chapteraccessionid": "NBK368396",
            "book": "nap21891",
            "navigation": "yes"
        },
        "4286974": {
            "uid": "4286974",
            "title": "Speaker Biographical Sketches",
            "pubdate": "2016/06/01 00:00",
            "id": "nap21861/appendix/appC/PMC",
            "accessionid": "NBK373280",
            "parents": "",
            "rtype": "appendix",
            "rid": "NBK373280",
            "text": "",
            "bookinfo": "&lt;Info&gt;&lt;Path&gt;&lt;Parent id=\"nap21861\" role=\"source\" type=\"book\" uid=\"4286970\"&gt;&lt;Title&gt;The Role of Public-Private Partnerships in Health Systems Strengthening: Workshop Summary&lt;/Title&gt;&lt;/Parent&gt;&lt;Self id=\"appC\" role=\"document\" type=\"appendix\" uid=\"4286974\"&gt;&lt;Title&gt;Speaker Biographical Sketches&lt;/Title&gt;&lt;/Self&gt;&lt;/Path&gt;&lt;Citation CitationType=\"Part\"&gt;&lt;MainRecord&gt;&lt;Title&gt;Speaker Biographical Sketches.&lt;/Title&gt;&lt;/MainRecord&gt;&lt;ParentRecord&gt;&lt;Title&gt;The Role of Public-Private Partnerships in Health Systems Strengthening: Workshop Summary.&lt;/Title&gt;&lt;Contributors&gt;Forum on Public-Private Partnerships for Global Health and Safety; Board on Global Health; Institute of Medicine; National Academies of Sciences, Engineering, and Medicine.&lt;/Contributors&gt;&lt;PublicationStatement&gt;Washington (DC): National Academies Press (US); 2016 Jun 1.&lt;/PublicationStatement&gt;&lt;/ParentRecord&gt;&lt;Location&gt;Appendix C&lt;/Location&gt;&lt;/Citation&gt;&lt;/Info&gt;",
            "bookid": 4286970,
            "bookaccessionid": "NBK373282",
            "chapterid": 4286974,
            "chapteraccessionid": "NBK373280",
            "book": "nap21861",
            "navigation": "yes"
        },
        "4287004": {
            "uid": "4287004",
            "title": "The Long-Term Picture for Health Systems: The Role of Public–Private Partnerships in Health Systems Strengthening",
            "pubdate": "2016/06/01 00:00",
            "id": "nap21861/appB/sec/sec_000067/PMC",
            "accessionid": "NBK373273",
            "parents": "",
            "rtype": "sec",
            "rid": "NBK373273/sec_000067",
            "text": "",
            "bookinfo": "&lt;Info&gt;&lt;Path&gt;&lt;Parent id=\"nap21861\" role=\"source\" type=\"book\" uid=\"4286970\"&gt;&lt;Title&gt;The Role of Public-Private Partnerships in Health Systems Strengthening: Workshop Summary&lt;/Title&gt;&lt;/Parent&gt;&lt;Parent id=\"appB\" role=\"document\" type=\"appendix\" uid=\"4286988\"&gt;&lt;Title&gt;Workshop Agenda&lt;/Title&gt;&lt;/Parent&gt;&lt;Self id=\"sec_000067\" role=\"object\" type=\"sec\" uid=\"4287004\"&gt;&lt;Title&gt;The Long-Term Picture for Health Systems: The Role of Public&amp;#x2013;Private Partnerships in Health Systems Strengthening&lt;/Title&gt;&lt;/Self&gt;&lt;/Path&gt;&lt;Citation CitationType=\"Object\"&gt;&lt;MainRecord&gt;&lt;Title&gt;The Long-Term Picture for Health Systems: The Role of Public&amp;#x2013;Private Partnerships in Health Systems Strengthening.&lt;/Title&gt;&lt;/MainRecord&gt;&lt;ParentRecord&gt;&lt;Title&gt;The Role of Public-Private Partnerships in Health Systems Strengthening: Workshop Summary.&lt;/Title&gt;&lt;Contributors&gt;Forum on Public-Private Partnerships for Global Health and Safety; Board on Global Health; Institute of Medicine; National Academies of Sciences, Engineering, and Medicine.&lt;/Contributors&gt;&lt;PublicationStatement&gt;Washington (DC): National Academies Press (US); 2016 Jun 1.&lt;/PublicationStatement&gt;&lt;/ParentRecord&gt;&lt;Location&gt;Appendix  B, Workshop Agenda&lt;/Location&gt;&lt;/Citation&gt;&lt;/Info&gt;",
            "bookid": 4286970,
            "bookaccessionid": "NBK373282",
            "chapterid": 4286988,
            "chapteraccessionid": "NBK373273",
            "book": "nap21861",
            "navigation": "yes"
        },
        "4287072": {
            "uid": "4287072",
            "title": "SCALING UP AND SUSTAINING PARTNERSHIPS FOR HUMAN RESOURCES FOR HEALTH",
            "pubdate": "2016/06/01 00:00",
            "id": "nap21861/ch7/sec/sec_000050/PMC",
            "accessionid": "NBK373288",
            "parents": "",
            "rtype": "sec",
            "rid": "NBK373288/sec_000050",
            "text": "",
            "bookinfo": "&lt;Info&gt;&lt;Path&gt;&lt;Parent id=\"nap21861\" role=\"source\" type=\"book\" uid=\"4286970\"&gt;&lt;Title&gt;The Role of Public-Private Partnerships in Health Systems Strengthening: Workshop Summary&lt;/Title&gt;&lt;/Parent&gt;&lt;Parent id=\"ch7\" role=\"document\" type=\"chapter\" uid=\"4287066\"&gt;&lt;Title&gt;Sustaining and Increasing Long-Term Investments in Health Systems&lt;/Title&gt;&lt;/Parent&gt;&lt;Self id=\"sec_000050\" role=\"object\" type=\"sec\" uid=\"4287072\"&gt;&lt;Title&gt;SCALING UP AND SUSTAINING PARTNERSHIPS FOR HUMAN RESOURCES FOR HEALTH&lt;/Title&gt;&lt;/Self&gt;&lt;/Path&gt;&lt;Citation CitationType=\"Object\"&gt;&lt;MainRecord&gt;&lt;Title&gt;SCALING UP AND SUSTAINING PARTNERSHIPS FOR HUMAN RESOURCES FOR HEALTH.&lt;/Title&gt;&lt;/MainRecord&gt;&lt;ParentRecord&gt;&lt;Title&gt;The Role of Public-Private Partnerships in Health Systems Strengthening: Workshop Summary.&lt;/Title&gt;&lt;Contributors&gt;Forum on Public-Private Partnerships for Global Health and Safety; Board on Global Health; Institute of Medicine; National Academies of Sciences, Engineering, and Medicine.&lt;/Contributors&gt;&lt;PublicationStatement&gt;Washington (DC): National Academies Press (US); 2016 Jun 1.&lt;/PublicationStatement&gt;&lt;/ParentRecord&gt;&lt;Location&gt;7, Sustaining and Increasing Long-Term Investments in Health Systems&lt;/Location&gt;&lt;/Citation&gt;&lt;/Info&gt;",
            "bookid": 4286970,
            "bookaccessionid": "NBK373282",
            "chapterid": 4287066,
            "chapteraccessionid": "NBK373288",
            "book": "nap21861",
            "navigation": "yes"
        },
        "4287078": {
            "uid": "4287078",
            "title": "Reviewers",
            "pubdate": "2016/06/01 00:00",
            "id": "nap21861/sec/sec_000006/PMC",
            "accessionid": "NBK373285",
            "parents": "",
            "rtype": "sec",
            "rid": "NBK373285",
            "text": "",
            "bookinfo": "&lt;Info&gt;&lt;Path&gt;&lt;Parent id=\"nap21861\" role=\"source\" type=\"book\" uid=\"4286970\"&gt;&lt;Title&gt;The Role of Public-Private Partnerships in Health Systems Strengthening: Workshop Summary&lt;/Title&gt;&lt;/Parent&gt;&lt;Self id=\"sec_000006\" role=\"document\" type=\"sec\" uid=\"4287078\"&gt;&lt;Title&gt;Reviewers&lt;/Title&gt;&lt;/Self&gt;&lt;/Path&gt;&lt;Citation CitationType=\"Part\"&gt;&lt;MainRecord&gt;&lt;Title&gt;Reviewers.&lt;/Title&gt;&lt;/MainRecord&gt;&lt;ParentRecord&gt;&lt;Title&gt;The Role of Public-Private Partnerships in Health Systems Strengthening: Workshop Summary.&lt;/Title&gt;&lt;Contributors&gt;Forum on Public-Private Partnerships for Global Health and Safety; Board on Global Health; Institute of Medicine; National Academies of Sciences, Engineering, and Medicine.&lt;/Contributors&gt;&lt;PublicationStatement&gt;Washington (DC): National Academies Press (US); 2016 Jun 1.&lt;/PublicationStatement&gt;&lt;/ParentRecord&gt;&lt;/Citation&gt;&lt;/Info&gt;",
            "bookid": 4286970,
            "bookaccessionid": "NBK373282",
            "chapterid": 4287078,
            "chapteraccessionid": "NBK373285",
            "book": "nap21861",
            "navigation": "yes"
        },
        "4288582": {
            "uid": "4288582",
            "title": "Speaker Biographical Sketches",
            "pubdate": "2016/06/06 00:00",
            "id": "nap21747/appendix/appB/PMC",
            "accessionid": "NBK373397",
            "parents": "",
            "rtype": "appendix",
            "rid": "NBK373397",
            "text": "",
            "bookinfo": "&lt;Info&gt;&lt;Path&gt;&lt;Parent id=\"nap21747\" role=\"source\" type=\"book\" uid=\"4288580\"&gt;&lt;Title&gt;Approaches to Universal Health Coverage and Occupational Health and Safety for the Informal Workforce in Developing Countries: Workshop Summary&lt;/Title&gt;&lt;/Parent&gt;&lt;Self id=\"appB\" role=\"document\" type=\"appendix\" uid=\"4288582\"&gt;&lt;Title&gt;Speaker Biographical Sketches&lt;/Title&gt;&lt;/Self&gt;&lt;/Path&gt;&lt;Citation CitationType=\"Part\"&gt;&lt;MainRecord&gt;&lt;Title&gt;Speaker Biographical Sketches.&lt;/Title&gt;&lt;/MainRecord&gt;&lt;ParentRecord&gt;&lt;Title&gt;Approaches to Universal Health Coverage and Occupational Health and Safety for the Informal Workforce in Developing Countries: Workshop Summary.&lt;/Title&gt;&lt;Contributors&gt;Forum on Public-Private Partnerships for Global Health and Safety; Board on Global Health; Institute of Medicine; National Academies of Sciences, Engineering, and Medicine.&lt;/Contributors&gt;&lt;PublicationStatement&gt;Washington (DC): National Academies Press (US); 2016 Jun 6.&lt;/PublicationStatement&gt;&lt;/ParentRecord&gt;&lt;Location&gt;Appendix B&lt;/Location&gt;&lt;/Citation&gt;&lt;/Info&gt;",
            "bookid": 4288580,
            "bookaccessionid": "NBK373406",
            "chapterid": 4288582,
            "chapteraccessionid": "NBK373397",
            "book": "nap21747",
            "navigation": "yes"
        },
        "4288806": {
            "uid": "4288806",
            "title": "A New Regulatory Framework for the Nation's Investment in Academic Research",
            "pubdate": "2016/07/27 00:00",
            "id": "nap21824/chapter/ch7/PMC",
            "accessionid": "NBK373569",
            "parents": "",
            "rtype": "chapter",
            "rid": "NBK373569",
            "text": "",
            "bookinfo": "&lt;Info&gt;&lt;Path&gt;&lt;Parent id=\"nap21824\" role=\"source\" type=\"book\" uid=\"4287296\"&gt;&lt;Title&gt;Optimizing the Nation's Investment in Academic Research: A New Regulatory Framework for the 21st Century&lt;/Title&gt;&lt;/Parent&gt;&lt;Self id=\"ch7\" role=\"document\" type=\"chapter\" uid=\"4288806\"&gt;&lt;Title&gt;A New Regulatory Framework for the Nation's Investment in Academic Research&lt;/Title&gt;&lt;/Self&gt;&lt;/Path&gt;&lt;Citation CitationType=\"Part\"&gt;&lt;MainRecord&gt;&lt;Title&gt;A New Regulatory Framework for the Nation's Investment in Academic Research.&lt;/Title&gt;&lt;/MainRecord&gt;&lt;ParentRecord&gt;&lt;Title&gt;Optimizing the Nation's Investment in Academic Research: A New Regulatory Framework for the 21st Century.&lt;/Title&gt;&lt;Contributors&gt;Committee on Federal Research Regulations and Reporting Requirements: A New Framework for Research Universities in the 21st Century; Committee on Science, Technology, and Law; Board on Higher Education and Workforce; Policy and Global Affairs; National Academies of Sciences, Engineering, and Medicine.&lt;/Contributors&gt;&lt;PublicationStatement&gt;Washington (DC): National Academies Press (US); 2016 Jul 27.&lt;/PublicationStatement&gt;&lt;/ParentRecord&gt;&lt;/Citation&gt;&lt;/Info&gt;",
            "bookid": 4287296,
            "bookaccessionid": "NBK373252",
            "chapterid": 4288806,
            "chapteraccessionid": "NBK373569",
            "book": "nap21824",
            "navigation": "yes"
        },
        "4361506": {
            "uid": "4361506",
            "title": "Guideline Development Group (GDG)",
            "pubdate": "2016/01/01 00:00",
            "id": "who250796/annex1/sec/annex1.s2/PMC",
            "accessionid": "NBK409106",
            "parents": "",
            "rtype": "sec",
            "rid": "NBK409106/annex1.s2",
            "text": "",
            "bookinfo": "&lt;Info&gt;&lt;Path&gt;&lt;Parent id=\"who250796\" role=\"source\" type=\"book\" uid=\"4361422\"&gt;&lt;Title&gt;WHO Recommendations on Antenatal Care for a Positive Pregnancy Experience&lt;/Title&gt;&lt;/Parent&gt;&lt;Parent id=\"annex1\" role=\"document\" type=\"appendix\" uid=\"4361502\"&gt;&lt;Title&gt;External experts and WHO staff involved in the preparation of this guideline&lt;/Title&gt;&lt;/Parent&gt;&lt;Self id=\"annex1.s2\" role=\"object\" type=\"sec\" uid=\"4361506\"&gt;&lt;Title&gt;Guideline Development Group (GDG)&lt;/Title&gt;&lt;/Self&gt;&lt;/Path&gt;&lt;Citation CitationType=\"Object\"&gt;&lt;MainRecord&gt;&lt;Title&gt;Guideline Development Group (GDG).&lt;/Title&gt;&lt;/MainRecord&gt;&lt;ParentRecord&gt;&lt;Title&gt;WHO Recommendations on Antenatal Care for a Positive Pregnancy Experience.&lt;/Title&gt;&lt;PublicationStatement&gt;Geneva: World Health Organization; 2016.&lt;/PublicationStatement&gt;&lt;/ParentRecord&gt;&lt;Location&gt;Annex  1, External experts and WHO staff involved in the preparation of this guideline&lt;/Location&gt;&lt;/Citation&gt;&lt;/Info&gt;",
            "bookid": 4361422,
            "bookaccessionid": "NBK409108",
            "chapterid": 4361502,
            "chapteraccessionid": "NBK409106",
            "book": "who250796",
            "navigation": "yes"
        },
        "4384916": {
            "uid": "4384916",
            "title": "TYPES OF SGES AND THEIR CONSEQUENCES",
            "pubdate": "2011/01/01 00:00",
            "id": "nap13223/ch10/sec/ch10.s2/PMC",
            "accessionid": "NBK424883",
            "parents": "",
            "rtype": "sec",
            "rid": "NBK424883/ch10.s2",
            "text": "",
            "bookinfo": "&lt;Info&gt;&lt;Path&gt;&lt;Parent id=\"nap13223\" role=\"source\" type=\"book\" uid=\"4384702\"&gt;&lt;Title&gt;In the Light of Evolution: Volume V: Cooperation and Conflict&lt;/Title&gt;&lt;/Parent&gt;&lt;Parent id=\"ch10\" role=\"document\" type=\"chapter\" uid=\"4384912\"&gt;&lt;Title&gt;Selfish Genetic Elements, Genetic Conflict, and Evolutionary Innovation&lt;/Title&gt;&lt;/Parent&gt;&lt;Self id=\"ch10.s2\" role=\"object\" type=\"sec\" uid=\"4384916\"&gt;&lt;Title&gt;TYPES OF SGES AND THEIR CONSEQUENCES&lt;/Title&gt;&lt;/Self&gt;&lt;/Path&gt;&lt;Citation CitationType=\"Object\"&gt;&lt;MainRecord&gt;&lt;Title&gt;TYPES OF SGES AND THEIR CONSEQUENCES.&lt;/Title&gt;&lt;/MainRecord&gt;&lt;ParentRecord&gt;&lt;Title&gt;In the Light of Evolution: Volume V: Cooperation and Conflict.&lt;/Title&gt;&lt;Contributors&gt;Strassman JE, Queller DC, Avise JC, et al., editors.&lt;/Contributors&gt;&lt;PublicationStatement&gt;Washington (DC): National Academies Press (US); 2011.&lt;/PublicationStatement&gt;&lt;/ParentRecord&gt;&lt;Location&gt;10, Selfish Genetic Elements, Genetic Conflict, and Evolutionary Innovation&lt;/Location&gt;&lt;/Citation&gt;&lt;/Info&gt;",
            "bookid": 4384702,
            "bookaccessionid": "NBK424880",
            "chapterid": 4384912,
            "chapteraccessionid": "NBK424883",
            "book": "nap13223",
            "navigation": "yes"
        },
        "uids": [
            "4384916",
            "4361506",
            "4288806",
            "4288582",
            "4287078",
            "4287072",
            "4287004",
            "4286974",
            "4284246",
            "4284158",
            "4263754",
            "4229776",
            "4211182",
            "4184400",
            "4141704",
            "4141622",
            "4141618",
            "4141616",
            "4141596",
            "4141594"
        ]
    }
} ;

let book =  {
    "4141594": {
        "uid": "4141594",
        "title": "Table",
        "pubdate": "2015/10/22 00:00",
        "id": "nap21799/appB/table/tab_appB-2/PMC",
        "accessionid": "NBK327243",
        "parents": "",
        "rtype": "table",
        "rid": "NBK327243/table/tab_appB-2",
        "text": "",
        "bookinfo": "&lt;Info&gt;&lt;Path&gt;&lt;Parent id=\"nap21799\" role=\"source\" type=\"book\" uid=\"4141572\"&gt;&lt;Title&gt;Using Existing Platforms to Integrate and Coordinate Investments for Children: Summary of a Joint Workshop by the National Academies of Sciences, Engineering, and Medicine; Centre for Health Education and Health Promotion; and Wu Yee Sun College of the Chinese University of Hong Kong&lt;/Title&gt;&lt;/Parent&gt;&lt;Parent id=\"appB\" role=\"document\" type=\"appendix\" uid=\"4141590\"&gt;&lt;Title&gt;Workshop Agenda&lt;/Title&gt;&lt;/Parent&gt;&lt;Self id=\"tab_appB-2\" role=\"object\" type=\"table\" uid=\"4141594\"&gt;&lt;Title&gt;Table&lt;/Title&gt;&lt;/Self&gt;&lt;/Path&gt;&lt;Citation CitationType=\"Object\"&gt;&lt;MainRecord&gt;&lt;Title&gt;Table.&lt;/Title&gt;&lt;/MainRecord&gt;&lt;ParentRecord&gt;&lt;Title&gt;Using Existing Platforms to Integrate and Coordinate Investments for Children: Summary of a Joint Workshop by the National Academies of Sciences, Engineering, and Medicine; Centre for Health Education and Health Promotion; and Wu Yee Sun College of the Chinese University of Hong Kong.&lt;/Title&gt;&lt;Contributors&gt;Forum on Investing in Young Children Globally; Board on Global Health; Board on Children, Youth, and Families; Institute of Medicine; Division of Behavioral and Social Sciences and Education; National Academies of Sciences, Engineering, and Medicine.&lt;/Contributors&gt;&lt;PublicationStatement&gt;Washington (DC): National Academies Press (US); 2015 Oct 22.&lt;/PublicationStatement&gt;&lt;/ParentRecord&gt;&lt;Location&gt;Appendix  B, Workshop Agenda&lt;/Location&gt;&lt;/Citation&gt;&lt;/Info&gt;",
        "bookid": 4141572,
        "bookaccessionid": "NBK327252",
        "chapterid": 4141590,
        "chapteraccessionid": "NBK327243",
        "book": "nap21799",
        "navigation": "yes"
    },
    "4141596": {
        "uid": "4141596",
        "title": "Forum on Investing in Young Children Globally (iYCG) Workshop 4: Using Existing Platforms to Integrate and Coordinate Investments for Children",
        "pubdate": "2015/10/22 00:00",
        "id": "nap21799/appB/sec/sec_000049/PMC",
        "accessionid": "NBK327243",
        "parents": "",
        "rtype": "sec",
        "rid": "NBK327243/sec_000049",
        "text": "",
        "bookinfo": "&lt;Info&gt;&lt;Path&gt;&lt;Parent id=\"nap21799\" role=\"source\" type=\"book\" uid=\"4141572\"&gt;&lt;Title&gt;Using Existing Platforms to Integrate and Coordinate Investments for Children: Summary of a Joint Workshop by the National Academies of Sciences, Engineering, and Medicine; Centre for Health Education and Health Promotion; and Wu Yee Sun College of the Chinese University of Hong Kong&lt;/Title&gt;&lt;/Parent&gt;&lt;Parent id=\"appB\" role=\"document\" type=\"appendix\" uid=\"4141590\"&gt;&lt;Title&gt;Workshop Agenda&lt;/Title&gt;&lt;/Parent&gt;&lt;Self id=\"sec_000049\" role=\"object\" type=\"sec\" uid=\"4141596\"&gt;&lt;Title&gt;Forum on Investing in Young Children Globally (iYCG) Workshop 4: Using Existing Platforms to Integrate and Coordinate Investments for Children&lt;/Title&gt;&lt;/Self&gt;&lt;/Path&gt;&lt;Citation CitationType=\"Object\"&gt;&lt;MainRecord&gt;&lt;Title&gt;Forum on Investing in Young Children Globally (iYCG) Workshop 4: Using Existing Platforms to Integrate and Coordinate Investments for Children.&lt;/Title&gt;&lt;/MainRecord&gt;&lt;ParentRecord&gt;&lt;Title&gt;Using Existing Platforms to Integrate and Coordinate Investments for Children: Summary of a Joint Workshop by the National Academies of Sciences, Engineering, and Medicine; Centre for Health Education and Health Promotion; and Wu Yee Sun College of the Chinese University of Hong Kong.&lt;/Title&gt;&lt;Contributors&gt;Forum on Investing in Young Children Globally; Board on Global Health; Board on Children, Youth, and Families; Institute of Medicine; Division of Behavioral and Social Sciences and Education; National Academies of Sciences, Engineering, and Medicine.&lt;/Contributors&gt;&lt;PublicationStatement&gt;Washington (DC): National Academies Press (US); 2015 Oct 22.&lt;/PublicationStatement&gt;&lt;/ParentRecord&gt;&lt;Location&gt;Appendix  B, Workshop Agenda&lt;/Location&gt;&lt;/Citation&gt;&lt;/Info&gt;",
        "bookid": 4141572,
        "bookaccessionid": "NBK327252",
        "chapterid": 4141590,
        "chapteraccessionid": "NBK327243",
        "book": "nap21799",
        "navigation": "yes"
    },
    "4141616": {
        "uid": "4141616",
        "title": "Acronyms",
        "pubdate": "2015/10/22 00:00",
        "id": "nap21799/appendix/appA/PMC",
        "accessionid": "NBK327256",
        "parents": "",
        "rtype": "appendix",
        "rid": "NBK327256",
        "text": "",
        "bookinfo": "&lt;Info&gt;&lt;Path&gt;&lt;Parent id=\"nap21799\" role=\"source\" type=\"book\" uid=\"4141572\"&gt;&lt;Title&gt;Using Existing Platforms to Integrate and Coordinate Investments for Children: Summary of a Joint Workshop by the National Academies of Sciences, Engineering, and Medicine; Centre for Health Education and Health Promotion; and Wu Yee Sun College of the Chinese University of Hong Kong&lt;/Title&gt;&lt;/Parent&gt;&lt;Self id=\"appA\" role=\"document\" type=\"appendix\" uid=\"4141616\"&gt;&lt;Title&gt;Acronyms&lt;/Title&gt;&lt;/Self&gt;&lt;/Path&gt;&lt;Citation CitationType=\"Part\"&gt;&lt;MainRecord&gt;&lt;Title&gt;Acronyms.&lt;/Title&gt;&lt;/MainRecord&gt;&lt;ParentRecord&gt;&lt;Title&gt;Using Existing Platforms to Integrate and Coordinate Investments for Children: Summary of a Joint Workshop by the National Academies of Sciences, Engineering, and Medicine; Centre for Health Education and Health Promotion; and Wu Yee Sun College of the Chinese University of Hong Kong.&lt;/Title&gt;&lt;Contributors&gt;Forum on Investing in Young Children Globally; Board on Global Health; Board on Children, Youth, and Families; Institute of Medicine; Division of Behavioral and Social Sciences and Education; National Academies of Sciences, Engineering, and Medicine.&lt;/Contributors&gt;&lt;PublicationStatement&gt;Washington (DC): National Academies Press (US); 2015 Oct 22.&lt;/PublicationStatement&gt;&lt;/ParentRecord&gt;&lt;Location&gt;Appendix A&lt;/Location&gt;&lt;/Citation&gt;&lt;/Info&gt;",
        "bookid": 4141572,
        "bookaccessionid": "NBK327252",
        "chapterid": 4141616,
        "chapteraccessionid": "NBK327256",
        "book": "nap21799",
        "navigation": "yes"
    },
    "4141618": {
        "uid": "4141618",
        "title": "Using Existing Platforms to Integrate Services on the Ground",
        "pubdate": "2015/10/22 00:00",
        "id": "nap21799/chapter/ch5/PMC",
        "accessionid": "NBK327245",
        "parents": "",
        "rtype": "chapter",
        "rid": "NBK327245",
        "text": "",
        "bookinfo": "&lt;Info&gt;&lt;Path&gt;&lt;Parent id=\"nap21799\" role=\"source\" type=\"book\" uid=\"4141572\"&gt;&lt;Title&gt;Using Existing Platforms to Integrate and Coordinate Investments for Children: Summary of a Joint Workshop by the National Academies of Sciences, Engineering, and Medicine; Centre for Health Education and Health Promotion; and Wu Yee Sun College of the Chinese University of Hong Kong&lt;/Title&gt;&lt;/Parent&gt;&lt;Self id=\"ch5\" role=\"document\" type=\"chapter\" uid=\"4141618\"&gt;&lt;Title&gt;Using Existing Platforms to Integrate Services on the Ground&lt;/Title&gt;&lt;/Self&gt;&lt;/Path&gt;&lt;Citation CitationType=\"Part\"&gt;&lt;MainRecord&gt;&lt;Title&gt;Using Existing Platforms to Integrate Services on the Ground.&lt;/Title&gt;&lt;/MainRecord&gt;&lt;ParentRecord&gt;&lt;Title&gt;Using Existing Platforms to Integrate and Coordinate Investments for Children: Summary of a Joint Workshop by the National Academies of Sciences, Engineering, and Medicine; Centre for Health Education and Health Promotion; and Wu Yee Sun College of the Chinese University of Hong Kong.&lt;/Title&gt;&lt;Contributors&gt;Forum on Investing in Young Children Globally; Board on Global Health; Board on Children, Youth, and Families; Institute of Medicine; Division of Behavioral and Social Sciences and Education; National Academies of Sciences, Engineering, and Medicine.&lt;/Contributors&gt;&lt;PublicationStatement&gt;Washington (DC): National Academies Press (US); 2015 Oct 22.&lt;/PublicationStatement&gt;&lt;/ParentRecord&gt;&lt;/Citation&gt;&lt;/Info&gt;",
        "bookid": 4141572,
        "bookaccessionid": "NBK327252",
        "chapterid": 4141618,
        "chapteraccessionid": "NBK327245",
        "book": "nap21799",
        "navigation": "yes"
    },
    "4141622": {
        "uid": "4141622",
        "title": "HOLISTIC DEVELOPMENT AND LEARNING IN EARLY CHILDHOOD: INITIAL EXPERIENCES FROM BRAC",
        "pubdate": "2015/10/22 00:00",
        "id": "nap21799/ch5/sec/sec_000036/PMC",
        "accessionid": "NBK327245",
        "parents": "",
        "rtype": "sec",
        "rid": "NBK327245/sec_000036",
        "text": "",
        "bookinfo": "&lt;Info&gt;&lt;Path&gt;&lt;Parent id=\"nap21799\" role=\"source\" type=\"book\" uid=\"4141572\"&gt;&lt;Title&gt;Using Existing Platforms to Integrate and Coordinate Investments for Children: Summary of a Joint Workshop by the National Academies of Sciences, Engineering, and Medicine; Centre for Health Education and Health Promotion; and Wu Yee Sun College of the Chinese University of Hong Kong&lt;/Title&gt;&lt;/Parent&gt;&lt;Parent id=\"ch5\" role=\"document\" type=\"chapter\" uid=\"4141618\"&gt;&lt;Title&gt;Using Existing Platforms to Integrate Services on the Ground&lt;/Title&gt;&lt;/Parent&gt;&lt;Self id=\"sec_000036\" role=\"object\" type=\"sec\" uid=\"4141622\"&gt;&lt;Title&gt;HOLISTIC DEVELOPMENT AND LEARNING IN EARLY CHILDHOOD: INITIAL EXPERIENCES FROM BRAC&lt;/Title&gt;&lt;/Self&gt;&lt;/Path&gt;&lt;Citation CitationType=\"Object\"&gt;&lt;MainRecord&gt;&lt;Title&gt;HOLISTIC DEVELOPMENT AND LEARNING IN EARLY CHILDHOOD: INITIAL EXPERIENCES FROM BRAC.&lt;/Title&gt;&lt;/MainRecord&gt;&lt;ParentRecord&gt;&lt;Title&gt;Using Existing Platforms to Integrate and Coordinate Investments for Children: Summary of a Joint Workshop by the National Academies of Sciences, Engineering, and Medicine; Centre for Health Education and Health Promotion; and Wu Yee Sun College of the Chinese University of Hong Kong.&lt;/Title&gt;&lt;Contributors&gt;Forum on Investing in Young Children Globally; Board on Global Health; Board on Children, Youth, and Families; Institute of Medicine; Division of Behavioral and Social Sciences and Education; National Academies of Sciences, Engineering, and Medicine.&lt;/Contributors&gt;&lt;PublicationStatement&gt;Washington (DC): National Academies Press (US); 2015 Oct 22.&lt;/PublicationStatement&gt;&lt;/ParentRecord&gt;&lt;Location&gt;5, Using Existing Platforms to Integrate Services on the Ground&lt;/Location&gt;&lt;/Citation&gt;&lt;/Info&gt;",
        "bookid": 4141572,
        "bookaccessionid": "NBK327252",
        "chapterid": 4141618,
        "chapteraccessionid": "NBK327245",
        "book": "nap21799",
        "navigation": "yes"
    },
    "4141704": {
        "uid": "4141704",
        "title": "Biographical Sketches of Workshop Speakers",
        "pubdate": "2015/10/22 00:00",
        "id": "nap21799/appendix/chap48/PMC",
        "accessionid": "NBK327242",
        "parents": "",
        "rtype": "appendix",
        "rid": "NBK327242",
        "text": "",
        "bookinfo": "&lt;Info&gt;&lt;Path&gt;&lt;Parent id=\"nap21799\" role=\"source\" type=\"book\" uid=\"4141572\"&gt;&lt;Title&gt;Using Existing Platforms to Integrate and Coordinate Investments for Children: Summary of a Joint Workshop by the National Academies of Sciences, Engineering, and Medicine; Centre for Health Education and Health Promotion; and Wu Yee Sun College of the Chinese University of Hong Kong&lt;/Title&gt;&lt;/Parent&gt;&lt;Self id=\"chap48\" role=\"document\" type=\"appendix\" uid=\"4141704\"&gt;&lt;Title&gt;Biographical Sketches of Workshop Speakers&lt;/Title&gt;&lt;/Self&gt;&lt;/Path&gt;&lt;Citation CitationType=\"Part\"&gt;&lt;MainRecord&gt;&lt;Title&gt;Biographical Sketches of Workshop Speakers.&lt;/Title&gt;&lt;/MainRecord&gt;&lt;ParentRecord&gt;&lt;Title&gt;Using Existing Platforms to Integrate and Coordinate Investments for Children: Summary of a Joint Workshop by the National Academies of Sciences, Engineering, and Medicine; Centre for Health Education and Health Promotion; and Wu Yee Sun College of the Chinese University of Hong Kong.&lt;/Title&gt;&lt;Contributors&gt;Forum on Investing in Young Children Globally; Board on Global Health; Board on Children, Youth, and Families; Institute of Medicine; Division of Behavioral and Social Sciences and Education; National Academies of Sciences, Engineering, and Medicine.&lt;/Contributors&gt;&lt;PublicationStatement&gt;Washington (DC): National Academies Press (US); 2015 Oct 22.&lt;/PublicationStatement&gt;&lt;/ParentRecord&gt;&lt;Location&gt;Appendix C&lt;/Location&gt;&lt;/Citation&gt;&lt;/Info&gt;",
        "bookid": 4141572,
        "bookaccessionid": "NBK327252",
        "chapterid": 4141704,
        "chapteraccessionid": "NBK327242",
        "book": "nap21799",
        "navigation": "yes"
    }
};


 const uid = '4141594';

// get book info as JSON
let {result:{[uid]:{bookinfo:bookInfo}}} =  resp;
console.log('bookInfo', JSON.stringify(bookInfo));
let boStr = he.decode(bookInfo);
let bookJson = himalaya.parse(boStr);
console.log('bookJson', JSON.stringify(bookJson));

//get books by book accession  id
let {result:res} = resp;
let resultKeys =Object.keys(res);
console.log('resultKeys', JSON.stringify(resultKeys));

let {result:{uids:resKeys}} = resp;

console.log('resKeys', JSON.stringify(resKeys));
let out = {
    "NBK424880":[{
    "uid": "4384916",
        "title": "TYPES OF SGES AND THEIR CONSEQUENCES",
        "pubdate": "2011/01/01 00:00",
        "id": "nap13223/ch10/sec/ch10.s2/PMC",
        "accessionid": "NBK424883",
        "parents": "",
        "rtype": "sec",
        "rid": "NBK424883/ch10.s2",
        "text": "",
        "bookinfo": "&lt;Info&gt;&lt;Path&gt;&lt;Parent id=\"nap13223\" role=\"source\" type=\"book\" uid=\"4384702\"&gt;&lt;Title&gt;In the Light of Evolution: Volume V: Cooperation and Conflict&lt;/Title&gt;&lt;/Parent&gt;&lt;Parent id=\"ch10\" role=\"document\" type=\"chapter\" uid=\"4384912\"&gt;&lt;Title&gt;Selfish Genetic Elements, Genetic Conflict, and Evolutionary Innovation&lt;/Title&gt;&lt;/Parent&gt;&lt;Self id=\"ch10.s2\" role=\"object\" type=\"sec\" uid=\"4384916\"&gt;&lt;Title&gt;TYPES OF SGES AND THEIR CONSEQUENCES&lt;/Title&gt;&lt;/Self&gt;&lt;/Path&gt;&lt;Citation CitationType=\"Object\"&gt;&lt;MainRecord&gt;&lt;Title&gt;TYPES OF SGES AND THEIR CONSEQUENCES.&lt;/Title&gt;&lt;/MainRecord&gt;&lt;ParentRecord&gt;&lt;Title&gt;In the Light of Evolution: Volume V: Cooperation and Conflict.&lt;/Title&gt;&lt;Contributors&gt;Strassman JE, Queller DC, Avise JC, et al., editors.&lt;/Contributors&gt;&lt;PublicationStatement&gt;Washington (DC): National Academies Press (US); 2011.&lt;/PublicationStatement&gt;&lt;/ParentRecord&gt;&lt;Location&gt;10, Selfish Genetic Elements, Genetic Conflict, and Evolutionary Innovation&lt;/Location&gt;&lt;/Citation&gt;&lt;/Info&gt;",
        "bookid": 4384702,
        "bookaccessionid": "NBK424880",
        "chapterid": 4384912,
        "chapteraccessionid": "NBK424883",
        "book": "nap13223",
        "navigation": "yes"
},{"uid": "4384916",
    "title": "TYPES OF SGES AND THEIR CONSEQUENCES",
    "pubdate": "2011/01/01 00:00",
    "id": "nap13223/ch10/sec/ch10.s2/PMC",
    "accessionid": "NBK424883",
    "parents": "",
    "rtype": "sec",
    "rid": "NBK424883/ch10.s2",
    "text": "",
    "bookinfo": "&lt;Info&gt;&lt;Path&gt;&lt;Parent id=\"nap13223\" role=\"source\" type=\"book\" uid=\"4384702\"&gt;&lt;Title&gt;In the Light of Evolution: Volume V: Cooperation and Conflict&lt;/Title&gt;&lt;/Parent&gt;&lt;Parent id=\"ch10\" role=\"document\" type=\"chapter\" uid=\"4384912\"&gt;&lt;Title&gt;Selfish Genetic Elements, Genetic Conflict, and Evolutionary Innovation&lt;/Title&gt;&lt;/Parent&gt;&lt;Self id=\"ch10.s2\" role=\"object\" type=\"sec\" uid=\"4384916\"&gt;&lt;Title&gt;TYPES OF SGES AND THEIR CONSEQUENCES&lt;/Title&gt;&lt;/Self&gt;&lt;/Path&gt;&lt;Citation CitationType=\"Object\"&gt;&lt;MainRecord&gt;&lt;Title&gt;TYPES OF SGES AND THEIR CONSEQUENCES.&lt;/Title&gt;&lt;/MainRecord&gt;&lt;ParentRecord&gt;&lt;Title&gt;In the Light of Evolution: Volume V: Cooperation and Conflict.&lt;/Title&gt;&lt;Contributors&gt;Strassman JE, Queller DC, Avise JC, et al., editors.&lt;/Contributors&gt;&lt;PublicationStatement&gt;Washington (DC): National Academies Press (US); 2011.&lt;/PublicationStatement&gt;&lt;/ParentRecord&gt;&lt;Location&gt;10, Selfish Genetic Elements, Genetic Conflict, and Evolutionary Innovation&lt;/Location&gt;&lt;/Citation&gt;&lt;/Info&gt;",
    "bookid": 4384702,
    "bookaccessionid": "NBK424880",
    "chapterid": 4384912,
    "chapteraccessionid": "NBK424883",
    "book": "nap13223",
    "navigation": "yes"
}]
};
let resArray = [];
let bookAccessionIds = new Map();
resKeys.forEach((objkey,indx, keys)=> {
    let bookAccessionId = res[objkey].bookaccessionid;
     bookAccessionIds.set(bookAccessionId,[]);
    let v = bookAccessionIds.get(bookAccessionId);
    v.push(res[objkey]);
    bookAccessionIds.set(bookAccessionId,v);
    });
console.log('bookAccessionIds lenght ', bookAccessionIds.size);

bookAccessionIds.forEach(function(value, key) {
    console.log(key + ' = ' + value);
});

